recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        - applications::create_var_chef_cache
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - nodejs::default                      # Installs nodejs and installs all nodejs packages mentioned in the nodejs:apps attribute
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
attributes:
    homebrewalt:
        cask_apps:
            - google-chrome
        cask_fonts:   
            - inconsolata
    nodejs:
        apps:
            - bower
